export const data = [
  {
    imagesUrl: "https://m.media-amazon.com/images/I/615XO7VlPLL._AC_UF894,1000_QL80_.jpg",
    imageTitles: "Steel Series",
    cost: "$142",
    action: "Add to Cart",
    numberOfProd: "",
  },
  {
    imagesUrl: "https://m.media-amazon.com/images/I/61eFyV4WLLL._AC_UF894,1000_QL80_.jpg",
    imageTitles: "Skull Candy",
    cost: "$99",
    action: "Add to Cart",
    numberOfProd: "",
  },
  {
    imagesUrl: "https://m.media-amazon.com/images/I/61otYZ1ZA9L._AC_UF894,1000_QL80_.jpg",
    imageTitles: "Steel Series New Arctis",
    cost: "$59",
    action: "Add to Cart",
    numberOfProd: "",
  },
  {
    imagesUrl: "https://m.media-amazon.com/images/I/71-+0U8z-ZL._AC_UF894,1000_QL80_.jpg",
    imageTitles: "Corsair HS65 SURROUND",
    cost: "$39",
    action: "Add to Cart",
    numberOfProd: "",
  },
  {
    imagesUrl: "https://m.media-amazon.com/images/I/61exUSWiSoL._AC_UF894,1000_QL80_.jpg",
    imageTitles: "Razer BlackShark V2 Pro",
    cost: "$198",
    action: "Add to Cart",
    numberOfProd: "",
  },
  {
    imagesUrl: "https://gamextreme.ph/cdn/shop/products/1_61d96251-9335-4d97-89ea-93cb54ef38a9_1024x1024.png?v=1669345684",
    imageTitles: "5 Hybrid Mechanical Gaming Keyboard",
    cost: "$74",
    action: "Add to Cart",
    numberOfProd: "",
  },
  {
    imagesUrl: "https://stormrigs.in/wp-content/uploads/2020/10/Aurora_2-min-1000x1000-1.jpg",
    imageTitles: "Compact Mechanical Gaming Keyboard",
    cost: "$79",
    action: "Add to Cart",
    numberOfProd: "",
  },
  {
    imagesUrl: "https://technology2you.com.au/wp-content/uploads/2022/10/BLOB820R.jpg",
    imageTitles: "MegaGee Mechanical Gaming Keyboard",
    cost: "$29",
    action: "Add to Cart",
    numberOfProd: "",
  },
  {
    imagesUrl: "https://stormrigs.in/wp-content/uploads/2020/10/Aurora_2-min-1000x1000-1.jpg",
    imageTitles: "Hustman Tenkeyless Gaming Keyboard",
    cost: "$109",
    action: "Add to Cart",
    numberOfProd: "",
  },
  {
    imagesUrl: "https://www.justop.com/user/products/large/sumvision-acies-mechanical-gaming-keyboard-01.jpg",
    imageTitles: "Longitech G Pro Gaming Keyboard",
    cost: "$79",
    action: "Add to Cart",
    numberOfProd: "",
  },
  {
    imagesUrl: "https://m.media-amazon.com/images/I/71M307k1bpL.jpg",
    imageTitles: "Rival 5 Gaming Mouse",
    cost: "$35",
    action: "Add to Cart",
    numberOfProd: "",
  },
  {
    imagesUrl: "https://m.media-amazon.com/images/I/61O4M0T5oOL.jpg",
    imageTitles: "Redragon M612 Preditor RGB Gaming Mouse",
    cost: "$19",
    action: "Add to Cart",
    numberOfProd: "",
  },
  {
    imagesUrl: "https://www.startech.com.bd/image/cache/catalog/mouse/xtrike-me/gm-414/gm-414-01-500x500.jpg",
    imageTitles: "Razer Basilick V3 Gaming Mouse",
    cost: "$23",
    action: "Add to Cart",
    numberOfProd: "",
  },
  {
    imagesUrl: "https://www.globalbrand.com.bd/image/cache/catalog/MOUSE/RAPOO/Rapoo-VT9PRO-Lightweight-Dual-Mode-Wireless-Gaming-Mouse-3-320x320.jpg",
    imageTitles: "Razor DeathAdder Essential Gaming Mouse",
    cost: "$49",
    action: "Add to Cart",
    numberOfProd: "",
  },
  {
    imagesUrl: "https://tecknet.com/cdn/shop/products/TECKNETWiredGamingMouse_PCGamingMice_16000DPIAdjustable_9ProgrammableModeswith7Buttons_800x.jpg?v=1656922904",
    imageTitles: "Longitech G5502 Gaming Mouse",
    cost: "$38",
    action: "Add to Cart",
    numberOfProd: "",
  },
  {
    imagesUrl: "https://m.media-amazon.com/images/I/61t4mpabO+L._AC_UF1000,1000_QL80_.jpg",
    imageTitles: "X Rocker Pedestal Gaming Chair",
    cost: "$152",
    action: "Add to Cart",
    numberOfProd: "",
  },
  {
    imagesUrl: "https://m.media-amazon.com/images/I/71HS9r2wPvL.jpg",
    imageTitles: "S*Max Fabric Gaming Chair",
    cost: "$199",
    action: "Add to Cart",
    numberOfProd: "",
  },
  {
    imagesUrl: "https://m.media-amazon.com/images/I/81e6MqCc3GL.jpg",
    imageTitles: "S*Max Fabric Gaming Chair",
    cost: "$199",
    action: "Add to Cart",
    numberOfProd: "",
  },
  {
    imagesUrl: "https://m.media-amazon.com/images/I/61BDXXpgWYL._AC_UF894,1000_QL80_.jpg",
    imageTitles: "Vigosit Gaming Chair",
    cost: "$189",
    action: "Add to Cart",
    numberOfProd: "",
  },
  {
    imagesUrl: "https://m.media-amazon.com/images/I/61x3LXynSFL._AC_UF894,1000_QL80_.jpg",
    imageTitles: "OHAHO Gaming Chair",
    cost: "$149",
    action: "Add to Cart",
    numberOfProd: "",
  },
];